export { default as Service } from "./Service"
export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as NotFound } from "./NotFound"
export { default as Navbar } from "./Navbar"
export { default as Footer } from "./Footer"